Fix some minor bugs and change email address
 - Update Extradata script to 1.0.1
    * Add copyright to the header.
    * Remove the % sign from some printf instances that is not needed.
    * Add shellcheck disable on some lines to silence the warning.

 - Update the systemd unit file VBoxAutostart@.service
    * Add more info and format the header.
    * Change the obsolete StandardOutput=syslog+console to StandardOutput=journal+console

 - Update systemd-vboxinit script to 2.1.8
   * Change the date format accordingly
   * Add Copyright to the header
   * Add additional curly braces to some variables to silence the
     error/warning from shellcheck
   * Fix bug, not executing the -d option/flag if there are no vms
     running

  - Update man page
   * Change the date format at the bottom of the man page
   * Highlight (change to bold fonts) some significant
     words/strings/text
   * Change the wiki/page/link of phpvirtualbox from sourceforge.net to
     its new github page

diff --git a/ExtraData b/ExtraData
--- a/ExtraData
+++ b/ExtraData
@@ -3,15 +3,16 @@
 # ============================================================================================ #
 #: Title           : ExtraData                                                                 #
 #: Sypnosis        : ExtraData                                                                 #
-#: Date Created    : Thu Oct 17 17:47:24 PHT 2013 / Thu Oct 17 09:48:11 UTC 2013               #
-#: Last Edit       : Thu Jan 16 10:49:02 PST 2020 / Thu Jan 16 02:49:02 UTC 2020               #
+#: Date Created    : Thu Oct 17 17:47:24 2013 +0800  /  Thu Oct 17 09:48:11 2013 UTC           #
+#: Last Edit       : Sat Mar 22 18:13:24 2025 +0800  /  Sat Mar 22 10:13:24 2025 UTC           #
 #: License         : GPLv3                                                                     #
-#: Version         : 1.0                                                                       #
-#: Author          : Jason V. Ferrer '<jetchisel@opensuse.org>'                                #
+#: Version         : 1.0.1                                                                     #
+#: Author          : Jason V. Ferrer '<jetchisel@gmail.com>'                                   #
 #: Description     : Set extradata to auto or manual of VirtualBox's vms.                      #
 #: Options         : NONE                                                                      #
 #: Home Page       : https://github.com/Jetchisel/VBoxAutostart                                #
 #: ExtComm         : clear,sleep,tput,VBoxManage                                               #
+#: Copyright       : Jason V. Ferrer 2013-2025                                                 #
 # ============================================================================================ #
 
 # ******************************************************************************************** #
@@ -104,12 +105,13 @@ StatusAll() {
 
 paused() {
   while :; do
-    printf "\n%s\n"
+    printf "\n\n"
     printf -v prompt "Press [c] to continue. "
     read -r -e -p "$prompt" -n1
     case $REPLY in
       [Cc]) clear
             return 0
+# shellcheck disable=SC2317
             clear;;
          *) printf "%s\n" "Invalid answer!" >&2
     esac
@@ -121,7 +123,8 @@ paused() {
 # ******************************************************************************************** #
 
 InValid() {
-  printf "\n%s" "Invalid option!" >&2
+  # printf "\n%s" "Invalid option!" >&2
+  printf "\nInvalid option!" >&2
 }
 
 # ******************************************************************************************** #
@@ -136,7 +139,7 @@ Wait(){
 # ******************************************************************************************** #
 #              Format the numbers in the array so it can be tested  in one line.               #
 # ******************************************************************************************** #
-
+# shellcheck disable=SC2145
 printf -v new "%s|" "@(${num[@]})"
 new=${new%|}
 
@@ -255,6 +258,7 @@ Auto() {
   clear
   while true; do
     VmsTotalAuto
+    # shellcheck disable=SC2053
      if  [[ ${REPLY} = $new ]]; then
        VBoxManage setextradata "${listvms[${REPLY}]}"  pvbx/startupMode auto
        printf -v single "[\"%s\"] " "${listvms[${REPLY}]}"
@@ -285,6 +289,7 @@ Manual() {
   clear
   while true; do
     VmsTotalManual
+      # shellcheck disable=SC2053
       if  [[ ${REPLY} = $new ]]; then
         VBoxManage setextradata "${listvms[${REPLY}]}"  pvbx/startupMode manual
         printf -v single "[\"%s\"] " "${listvms[${REPLY}]}"
@@ -297,6 +302,7 @@ Manual() {
         paused
       elif [[ ${REPLY} = [Rr] ]]; then
         return 0
+       # shellcheck disable=SC2317
         clear
       elif [[ ${REPLY} = [Qq] ]]; then
         clear
@@ -316,6 +322,7 @@ Status() {
   clear
    while true; do
      VmsTotalStatus
+       # shellcheck disable=SC2053
        if  [[ ${REPLY} = $new ]]; then
          result=$(VBoxManage getextradata "${listvms[${REPLY}]}"  pvbx/startupMode)
          printf '\n%s\n' "VirtualMachine[\"${listvms[${REPLY}]}\"]=${result#*: }"
@@ -326,6 +333,7 @@ Status() {
          paused
        elif [[ ${REPLY} = [Rr] ]]; then
          return 0
+      # shellcheck disable=SC2317
          clear
        elif [[ ${REPLY} = [Qq] ]]; then
          clear
diff --git a/systemd-vboxinit b/systemd-vboxinit
--- a/systemd-vboxinit
+++ b/systemd-vboxinit
@@ -5,15 +5,16 @@
 # ============================================================================================ #
 #: Title           : systemd-vboxinit                                                          #
 #: Sypnosis        : systemd-vboxinit OPTIONS                                                  #
-#: Date Created    : Wed Oct  2 07:57:25 PHT 2013 / Wed Oct  2 03:11:58 UTC 2013               #
-#: Last Edit       : Mon 04 Oct 2021 09:29:12 AM PST  /  Mon 04 Oct 2021 01:29:12 AM UTC       #
+#: Date Created    : Wed Oct 02 07:57:25 2013 +0800  /  Wed Oct 02 03:11:58 2013 UTC           #
+#: Last Edit       : Sat Mar 22 13:49:07 2025 +0800  /  Sat Mar 22 05:49:07 2025 UTC           #
 #: License         : GPLv3                                                                     #
-#: Version         : 2.1.7                                                                     #
-#: Author          : Jason V. Ferrer '<jetchisel@opensuse.org>'                                #
+#: Version         : 2.1.8                                                                     #
+#: Author          : Jason V. Ferrer '<jetchisel@gmail.com>'                                   #
 #: Description     : Auto start sessions when booting and save sessions when host is stopped.  #
 #: Options         : [about,stop,start,disable,license,help]                                   #
 #: Home Page       : https://github.com/Jetchisel/VBoxAutostart                                #
 #: ExtComm         : cat,find,grep,less,pgrep,systemctl,VBoxManage                             #
+#: Copyright       : Jason V. Ferrer 2013-2025                                                 #
 # ============================================================================================ #
 
 # ******************************************************************************************** #
@@ -79,7 +80,7 @@ for apps in "${ExtComm[@]}"; do
   fi
 done
 
-(( ${#Missing[@]} )) && die "$ExitMessage[${Missing[*]}] exiting now!" 127
+(( ${#Missing[@]} )) && die "${ExitMessage}[${Missing[*]}] exiting now!" 127
 
 # ******************************************************************************************** #
 #           Check if vboxdrv kernel module is loaded if not exit with an error.                #
@@ -286,14 +287,18 @@ disable() {
   local daemonpid
   local line
 
-  (( ${#uuids[@]} )) || die "No virtual machine runnning!"
-  while read -u8 -r line; do
-    ExtractVmNameUuid
-    printf '%s\n' "Saving machine '$VmName' state..."
-    SaveVms
-  done 8< <(ListRunningVms)
-
-  KillAllVBoxProcess && printf '\n%s\n' "${InstallMessage[@]}"
+  if (( ${#uuids[*]} )); then
+    while read -u8 -r line; do
+      ExtractVmNameUuid
+      printf '%s\n' "Saving machine '$VmName' state..."
+      SaveVms
+    done 8< <(ListRunningVms)
+  else
+    printf 'No virtual machine running!\n\n' >&2
+  fi
+  printf 'Trying to stop all VBox daemons!\n' &&
+  KillAllVBoxProcess &&
+  printf '\n%s\n' "${InstallMessage[@]}"
 }
 
 # ******************************************************************************************** #
